title: Data Engineer
title_keywords:
  - data engineer
  - platform engineer

required:
  - Python
  - SQL
  - Airflow
  - Hadoop
  - ETL

nice_to_have:
  - Spark
  - Kafka
  - Docker
  - Terraform
  - DBT
  - Redshift
  - AWS
  - TensorFlow

weights:
  required: 60
  nice: 40
