title: Data Analyst
title_keywords:
  - data analyst
  - business analyst

required:
  - Python
  - SQL
  - Tableau

nice_to_have:
  - Excel
  - Power BI
  - Looker
  - R
  - Statistics

weights:
  required: 60
  nice: 40